export const esimatesData = [
  {
    id: "1",
    name: "Project Alpha",
    tagLine: "Innovation at its best",
    estimate: "$10,000",
    customerName: "John Doe",
    customerEmail: "john.doe@example.com",
    customerPhone: "+1 234 567 8901",
    description: "A cutting-edge AI-driven analytics platform.",
  },
  {
    id: "2",
    name: "Project Beta",
    tagLine: "Building the future",
    estimate: "$15,500",
    customerName: "Jane Smith",
    customerEmail: "jane.smith@example.com",
    customerPhone: "+1 987 654 3210",
    description: "A next-gen e-commerce solution with AR integration.",
  },
  {
    id: "3",
    name: "Project Gamma",
    tagLine: "Engineering excellence",
    estimate: "N/A",
    customerName: "Robert Johnson",
    customerEmail: "robert.johnson@example.com",
    customerPhone: "+1 555 123 4567",
    description: "A cloud-based logistics and fleet management system.",
  },
  {
    id: "4",
    name: "Project Delta",
    tagLine: "Sustainable solutions",
    estimate: "$8,750",
    customerName: "Emily Davis",
    customerEmail: "emily.davis@example.com",
    customerPhone: "+1 444 987 6543",
    description: "An IoT-based smart farming application.",
  },
  {
    id: "5",
    name: "Project Omega",
    tagLine: "Revolutionizing industries",
    estimate: "$20,000",
    customerName: "Michael Brown",
    customerEmail: "michael.brown@example.com",
    customerPhone: "+1 333 789 1234",
    description: "A blockchain-based supply chain tracking system.",
  },
];

export const invoiceData = [
  {
    id: "1",
    number: "INV-001",
    name: "Project Alpha",
    estimate: "$10,000",
    customerName: "John Doe",
    customerEmail: "john.doe@example.com",
    customerPhone: "+1 234 567 8901",
    status: "Paid",
    projectDescription: "Development of a SaaS platform for analytics.",
  },
  {
    id: "2",
    number: "INV-002",
    name: "Project Beta",
    estimate: "$15,500",
    customerName: "Jane Smith",
    customerEmail: "jane.smith@example.com",
    customerPhone: "+1 987 654 3210",
    status: "Pending",
    projectDescription: "E-commerce website with multi-vendor support.",
  },
  {
    id: "3",
    number: "INV-003",
    name: "Project Gamma",
    estimate: "N/A",
    customerName: "Robert Johnson",
    customerEmail: "robert.johnson@example.com",
    customerPhone: "+1 555 123 4567",
    status: "Draft",
    projectDescription: "Mobile app for real-time fitness tracking.",
  },
  {
    id: "4",
    number: "INV-004",
    name: "Project Delta",
    estimate: "$8,750",
    customerName: "Emily Davis",
    customerEmail: "emily.davis@example.com",
    customerPhone: "+1 444 987 6543",
    status: "Pending",
    projectDescription: "Corporate website redesign with CMS integration.",
  },
  {
    id: "5",
    number: "INV-005",
    name: "Project Omega",
    estimate: "$20,000",
    customerName: "Michael Brown",
    customerEmail: "michael.brown@example.com",
    customerPhone: "+1 333 789 1234",
    status: "Paid",
    projectDescription: "AI-powered chatbot development for customer support.",
  },
];
